package todolist;

import DAO.TDLdao;
import java.awt.event.KeyEvent;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author hp
 */
public class editFolder extends javax.swing.JDialog {

    private String name;
    private FolderLine fdLine;
    private FolderPanel fdPanel;
    private TDLdao dao = new TDLdao();

    /**
     * Creates new form editFolder
     */
    public editFolder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public editFolder(java.awt.Frame parent, boolean modal, FolderLine fdLine) {
        super(parent, modal);
        this.fdLine = fdLine;
        this.fdPanel = fdLine.getFolder();
        name = fdLine.getName();
        initComponents();
        int count = inputName.getText().length();
        countInput.setText(count + "/20");
    }

    public JTextField getTextField() {
        return inputName;
    }

    public void confirmEdited() {
        String oldName = this.name; // old Name
        name = inputName.getText(); // new Name
        String regex = "[0-9A-Za-zก-ฮ\\u0E31-\\u0E4C ]+";

        if (name.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please input the folder name.");
        } else if (name.length() > 20) {
            JOptionPane.showMessageDialog(null, "The name entered is too long. Please try again.");
        } else if (!Pattern.matches(regex, name)) {
            JOptionPane.showMessageDialog(null, "Special characters are not allowed.");
        } else { // process here

            dao.editSheet(oldName, name);

            // set New folder name
            fdLine.getFolder().setFolderTitle(name);
            fdLine.setName(name);
            fdLine.setNameBT(name);
            fdPanel.setFolderName(name);
            System.out.println(String.format("[%s] ", oldName) + "Change name to -->: " + String.format("[%s] ", name));

            // Update in NotiArea
            for (Task t : fdPanel.getAllTasks()) {
                NotiTask NT = t.getNTask();
                fdPanel.getHomepage().removefromNotiArea(NT);
                t.UpdateNotiPanel();
            }

            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editFDPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField(name);
        confirmBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        countInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Folder");

        editFDPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Folder name:");

        inputName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNameKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNameKeyTyped(evt);
            }
        });

        confirmBT.setBackground(new java.awt.Color(255, 49, 49));
        confirmBT.setForeground(new java.awt.Color(255, 255, 255));
        confirmBT.setText("Confirm");
        confirmBT.setFocusPainted(false);
        confirmBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTActionPerformed(evt);
            }
        });

        cancelBT.setBackground(new java.awt.Color(204, 204, 204));
        cancelBT.setText("Cancel");
        cancelBT.setFocusPainted(false);
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });

        countInput.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        countInput.setText("0/20");

        javax.swing.GroupLayout editFDPanelLayout = new javax.swing.GroupLayout(editFDPanel);
        editFDPanel.setLayout(editFDPanelLayout);
        editFDPanelLayout.setHorizontalGroup(
                editFDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editFDPanelLayout.createSequentialGroup()
                                .addGroup(editFDPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(editFDPanelLayout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(confirmBT)
                                                .addGap(29, 29, 29)
                                                .addComponent(cancelBT))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFDPanelLayout
                                                .createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(editFDPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                editFDPanelLayout.createSequentialGroup()
                                                                        .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                81,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(inputName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                246,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                editFDPanelLayout.createSequentialGroup()
                                                                        .addComponent(countInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(11, 11, 11)))))
                                .addContainerGap(61, Short.MAX_VALUE)));
        editFDPanelLayout.setVerticalGroup(
                editFDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editFDPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(editFDPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countInput, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addGroup(editFDPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(confirmBT)
                                        .addComponent(cancelBT))
                                .addContainerGap(18, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editFDPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editFDPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_inputNameKeyReleased
        int count = inputName.getText().length();
        countInput.setText(count + "/20");
    }// GEN-LAST:event_inputNameKeyReleased

    private void inputNameKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_inputNameKeyTyped
        int count = inputName.getText().length();
        if (count > 20) {
            String s = inputName.getText();
            s = s.substring(0, 20);
            inputName.setText(s);
        }

        if (count >= 20 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // ไม่อนุญาตให้พิมพ์เกิน 20 ตัวอักษร
        }
    }// GEN-LAST:event_inputNameKeyTyped

    private void inputNameKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_inputNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (dao.isSheetNameExists(inputName.getText())) {
                JOptionPane.showMessageDialog(null, "Folder name already exists.");
            } else {
                confirmEdited();
            }
        }
    }// GEN-LAST:event_inputNameKeyPressed

    private void confirmBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmBTActionPerformed
         if (dao.isSheetNameExists(inputName.getText())) {
                JOptionPane.showMessageDialog(null, "Folder name already exists.");
            } else {
                confirmEdited();
            }
    }// GEN-LAST:event_confirmBTActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBTActionPerformed
        this.dispose();
    }// GEN-LAST:event_cancelBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editFolder.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editFolder.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editFolder.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editFolder.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                editFolder dialog = new editFolder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private javax.swing.JButton confirmBT;
    private javax.swing.JLabel countInput;
    private javax.swing.JPanel editFDPanel;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
