package todolist;

import DAO.TDLdao;
import java.awt.CardLayout;
import java.io.Serializable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static todolist.HomePanel.currentFolder;

/**
 *
 * @author hp
 */
public class FolderLine extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private String name;
    private HomePanel homepanel;
    private FolderPanel folder;
    private TDLdao dao = new TDLdao();

    /**
     * Creates new form FolderLine
     */
    public FolderLine() {
        initComponents();
    }

    public FolderLine(HomePanel home, String name, FolderPanel folder) {
        initComponents();
        this.name = name;
        setNameBT(name);
        homepanel = home;
        this.folder = folder;
        folder.setFolderLine(this);
    }

    public void setNameBT(String name) {
        NameBT.setText(name);
    }

    public FolderPanel getFolder() {
        return folder;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameBT = new javax.swing.JButton();
        DelBT = new javax.swing.JButton();
        EditBT = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 145, 77));
        setMaximumSize(new java.awt.Dimension(590, 50));
        setMinimumSize(new java.awt.Dimension(590, 50));

        NameBT.setBackground(new java.awt.Color(255, 145, 77));
        NameBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameBT.setText(name);
        NameBT.setBorder(null);
        NameBT.setFocusPainted(false);
        NameBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBTActionPerformed(evt);
            }
        });

        DelBT.setBackground(new java.awt.Color(255, 49, 49));
        DelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-bin.png"))); // NOI18N
        DelBT.setBorder(null);
        DelBT.setFocusPainted(false);
        DelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBTActionPerformed(evt);
            }
        });

        EditBT.setBackground(new java.awt.Color(126, 217, 87));
        EditBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-text.png"))); // NOI18N
        EditBT.setBorder(null);
        EditBT.setFocusPainted(false);
        EditBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(NameBT, javax.swing.GroupLayout.PREFERRED_SIZE, 439,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(EditBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NameBT, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditBT, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(DelBT, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void EditBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EditBTActionPerformed
        new editFolder(null, true, this).show();

    }// GEN-LAST:event_EditBTActionPerformed

    private void DelBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DelBTActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to delete this folder?", "To Do List - " + name,
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {

            // Update in 
            
            
            for (Task t : folder.getAllTasks()) {
                
                NotiTask NT = t.getNTask();
                folder.getHomepage().removefromNotiArea(NT);
                

            }
            dao.deleteSheet(name);
            homepanel.deleteFolder(this, folder);
            homepanel.getFolderListLabel().setText(homepanel.currentFolder + " of 20 folders");

        }

    }// GEN-LAST:event_DelBTActionPerformed

    private void NameBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NameBTActionPerformed
        String cardname = NameBT.getText();
        ToDoList.cardPanel.add(folder, cardname);
        CardLayout card = (CardLayout) (ToDoList.cardPanel.getLayout());
        card.show(ToDoList.cardPanel, cardname);
        // ToDoList.showTotalCards(cardname);
    }// GEN-LAST:event_NameBTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelBT;
    private javax.swing.JButton EditBT;
    private javax.swing.JButton NameBT;
    // End of variables declaration//GEN-END:variables
}
