package todolist;

import DAO.TDLdao;
import java.awt.CardLayout;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;

import javax.swing.JScrollBar;

public class FolderPanel extends javax.swing.JPanel {
    private String name;
    private HomePanel homepanel;
    private FolderLine fdLine;
    private ArrayList<Task> tasks = new ArrayList<Task>();
    private TDLdao dao = new TDLdao();

    /**
     * Creates new form FolderPanel
     */
    public FolderPanel() {
        initComponents();
    }

    public FolderPanel(HomePanel homePanel, String name) {
        this.name = name;
        initComponents();
        this.homepanel = homePanel;

        // Increase speed of scrolling
        JScrollBar verticalScrollBar = TaskScroll.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(16);
    }

    public void setFolderName(String name) {
        this.name = name;
    }

    public String getFolderName() {
        return this.name;
    }

    public FolderLine getFolderLine() {
        return fdLine;
    }

    public void setFolderLine(FolderLine fdLine) {
        this.fdLine = fdLine;
    }

    public void setFolderTitle(String name) {
        fdTitle.setText(name);
    }

    public void UpdatePanel(Date date, String details) {
        Task t = new Task(date, details, this);
        tasks.add(t);

        dao.saveData(t);
        t.TaskUpdate();
        t.doNotiTask(t.getIsWarning(), t.getIsChecked());


        // Show in TaskArea
        TaskArea.add(t);
        TaskArea.revalidate();
        TaskArea.repaint();
    }

    public void UpdatePanel() {
        TaskArea.revalidate();
        TaskArea.repaint();
    }

    public JPanel getTaskArea() {
        return TaskArea;
    }

    public ArrayList<Task> getAllTasks() {
        return tasks;

    }

    public void createTask(String isChecked, String date, String details) {
        Task t = new Task(isChecked, date, details, this);
        tasks.add(t);

        dao.saveData(t); // save task

        // Show in TaskArea
        TaskArea.add(t);
        TaskArea.revalidate();
        TaskArea.repaint();
    }

    public void delThisTask(Task t) {
        for (int i = 0; i < tasks.size(); i++) {
            if (tasks.get(i) == t)
                tasks.remove(t);
        }
    }

    public Date changetoDateClass(String date) {

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        Date d = null;
        try {
            // แปลง String เป็น Date
            d = formatter.parse(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return d;
    }

    public String formatDate(Date selectedDate) {
        String formattedDate = " ";
        if (selectedDate != null) {
            // แปลงเป็น LocalDate และกำหนดรูปแบบวันที่ที่ต้องการ
            LocalDate localDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            formattedDate = localDate.format(formatter);
        }
        return formattedDate;
    }

    public HomePanel getHomepage() {
        return homepanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBT = new javax.swing.JButton();
        fdTitle = new javax.swing.JLabel();
        dateDisplay = new todolist.DateDisplay();
        addTask = new javax.swing.JButton();
        TaskScroll = new javax.swing.JScrollPane();
        TaskArea = new javax.swing.JPanel();
        editFolder = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 189, 89));
        setMaximumSize(new java.awt.Dimension(750, 800));
        setMinimumSize(new java.awt.Dimension(750, 800));

        backBT.setBackground(new java.awt.Color(254, 254, 254));
        backBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward.png"))); // NOI18N
        backBT.setBorder(null);
        backBT.setFocusPainted(false);
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        fdTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fdTitle.setForeground(new java.awt.Color(255, 255, 255));
        fdTitle.setText(name);
        fdTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addTask.setBackground(new java.awt.Color(255, 49, 49));
        addTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        addTask.setText("Add task");
        addTask.setBorder(null);
        addTask.setFocusPainted(false);
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });

        TaskScroll.setBorder(null);
        TaskScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TaskScroll.setAutoscrolls(true);
        TaskScroll.setMaximumSize(new java.awt.Dimension(600, 600));
        TaskScroll.setMinimumSize(new java.awt.Dimension(600, 600));
        TaskScroll.setPreferredSize(new java.awt.Dimension(600, 600));

        TaskArea.setLayout(new java.awt.GridLayout(100, 0, 0, 5));
        TaskScroll.setViewportView(TaskArea);

        editFolder.setBackground(new java.awt.Color(255, 189, 89));
        editFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-text.png"))); // NOI18N
        editFolder.setBorder(null);
        editFolder.setBorderPainted(false);
        editFolder.setFocusPainted(false);
        editFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(390, 390, 390))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(editFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 221,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)))
                                .addComponent(dateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(70, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TaskScroll, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addContainerGap(68, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(fdTitle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                61,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(editFolder,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(addTask,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(dateDisplay,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                70,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(15, 15, 15)))))
                                .addComponent(TaskScroll, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)));
    }// </editor-fold>//GEN-END:initComponents

    private void editFolderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editFolderActionPerformed
        new editFolder(null, true, fdLine).show();

    }// GEN-LAST:event_editFolderActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBTActionPerformed
        CardLayout card = (CardLayout) (ToDoList.cardPanel.getLayout());
        card.show(ToDoList.cardPanel, "Home");
    }// GEN-LAST:event_backBTActionPerformed

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addTaskActionPerformed
        new addTask(null, true, this).show();

    }// GEN-LAST:event_addTaskActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TaskArea;
    private javax.swing.JScrollPane TaskScroll;
    private javax.swing.JButton addTask;
    private javax.swing.JButton backBT;
    private todolist.DateDisplay dateDisplay;
    private javax.swing.JButton editFolder;
    private javax.swing.JLabel fdTitle;
    // End of variables declaration//GEN-END:variables
}
